variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe'
  XUNIT_PATH: packages\xunit.runner.console.2.4.1\tools\net452
  UNITTEST_FOLDER: '.\DevOpsHelloWorldMVCTest\bin\Release'
  
cache:
  paths:
  - packages/
  - Publish/
  - '%UNITTEST_FOLDER%'
  - '%XUNIT_PATH%'


stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - 'nuget restore'
    - 'MSBuild /p:Configuration=Release /clp:ErrorsOnly /m'
  artifacts:
      expire_in: 2 days
      paths:
      - '%UNITTEST_FOLDER%'
      - '%XUNIT_PATH%'
      - 'Publish/'

test_job:
  stage: test
  script:
   - '%XUNIT_PATH%\xunit.console.exe %UNITTEST_FOLDER%\DevOpsHelloWorldMVCTest.dll'
  dependencies:
    - build_job
    
deploy_job:
  stage: deploy
  script:
   - 'MSBuild DevOpsHelloWorld\DevOpsHelloWorld.csproj /p:DeployOnBuild=true /p:Configuration=Release /P:PublishProfile=PublishProfile.pubxml'
   - 'xcopy /y /s ".\DevOpsHelloWorld\Publish\*.*" "C:\inetpub\wwwroot\"'
  environment:   
   name: production
   url: http://13.66.21.90
  when: manual
